name: Build and Publish to Docker Hub

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: sonarcloud
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Determine next version
        id: version
        run: |
          # List tags from Docker Hub using the Docker CLI
          TAGS=$(curl -s -H "Authorization: Bearer ${DOCKERHUB_TOKEN}" "https://hub.docker.com/v2/repositories/${DOCKERHUB_USERNAME}/as221s6_t07_nexcoin/tags/?page_size=100" | jq -r '.results[].name' | grep "^v" | sort -V | tail -n1)

          # Check if we have a previous tag
          if [[ -z "$TAGS" ]]; then
            # Start from v1.0 if no previous tags found
            MAJOR=1
            MINOR=0
          else
            # Extract major and minor version numbers
            MAJOR=$(echo "$TAGS" | cut -d'.' -f1 | sed 's/v//')
            MINOR=$(echo "$TAGS" | cut -d'.' -f2)
            # Increment minor version up to 5, then reset and increment major
            if [[ "$MINOR" -lt 5 ]]; then
              MINOR=$((MINOR + 1))
            else
              MAJOR=$((MAJOR + 1))
              MINOR=0
            fi
          fi

          # Define the next tag
          NEXT_TAG="v${MAJOR}.${MINOR}"
          echo "Next Docker tag: $NEXT_TAG"
          echo "tag=$NEXT_TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/as221s6_t07_nexcoin:${{ env.tag }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/as221s6_t07_nexcoin:${{ env.tag }}
